spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
logging:
  level:
    root: info
    sql: debug
    'org.springframework.orm.jpa': debug
    'org.springframework.transaction': debug
    'io.d4e': debug
